name: Deploy to OVH server
on:
  push:
    branches:
      - "master"
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      BASE_PATH: portfolio

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo "${{ secrets.PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa
          ssh-keyscan -H 146.59.87.169 >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: Upload project files
        run: |
          rsync -avz --delete --exclude=".git" --exclude=".github" ./ ciuser@146.59.87.169:/var/www/websites/production/portfolio/
